services:
  db:
    image: postgres
    container_name: todolist-postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - 5445:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  app:
    build: ./todolist/
    container_name: todolist-app
    restart: always
    ports:
      - 3000:3000
    links:
      - db
  
  migrations:
    build: ./todolist/migrations/
    container_name: todolist-migrations
    links:
      - db
    depends_on:
      db:
        condition: service_healthy